image: python:2.7.11

pages:
  cache:
    paths:
    - vendor

  script:
  - curl -sf https://www.getlektor.com/install.sh | sh
  - lektor build --output-path public
  artifacts:
    paths:
    - public
  only:
  - master